[project]
name = "deepfake-audio-detection"
version = "0.1.0"
description = ""
authors = [
    {name = "João Victor Canavarro",email = "jvcanavarro@gmail.com"},
    {name = "Igor Matheus Moreira", email = "imatheus.sm@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
